### ISSUE TITLE
Create starter app

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/docs#114]
## Deliverable

We need a starter app that demonstrates the integration of sql.js, TypeORM, and localForage in an Ionic React Typescript browser app.
- [Ionic React](https://ionicframework.com/docs/react/quickstart)
- [sql.js](https://sql.js.org)
- [TypeORM](https://typeorm.io/)
- [localForage](https://github.com/localForage/localForage)

Build an Ionic React app that shows how to add and list `User`s by using TypeORM and sql.js. Use localForage to persist and restore the database.

## Repo

[cpg](https://github.com/etenlab/cpg) - All code should go in this repo. The app has been started and some empty files/components have been added. You will need to finish the files. You are free to add anything you need.

## Tasks

- [x] Add sql.js to the `DbService`. It should probably be private.
- [x] Add TypeORM to the `DbService`. It should expose properties and methods so the React components can perform ORM operations. Use the `models` folder to generate database schema and types for TypeORM.
- [x] Update the `UserAddForm.tsx` component to use the `DbService` to add a `User` to the database.
- [x] Update the `UserList.tsx` and `User.tsx` components to show the list of users in the database in a table view.
- [x] Update the `DbService` to export the database to a file and save it using localForage when the browser unloads the page.
- [x] Update the `DbService` to load the database on app init from localForage if one exists.

## User Story

As an unauthenticated user, I want to create a `User` using a form and then see a list of `User`s I have created in a table view.

## Success

1. I will play the role of the user in the user story and try to create and view Users.
2. I will review the code to ensure it is only using TypeORM to create schema and perform operations on Users.
3. I will refresh the app to ensure the user list persists across browser refreshes.
4. I will add new types in the `models` folder to ensure TypeORM uses them.
